apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uvc5m5wp7-java-quarkus 
  janus-idp.io/tekton: uvc5m5wp7-java-quarkus
  backstage.io/kubernetes-id: uvc5m5wp7-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uvc5m5wp7-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml