apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uvc5m5wp7-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uvc5m5wp7-java-quarkus-gitops