apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uvc5m5wp7-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:bcfd6e40c4d00c78d6459b6b864278e646c89eb8@sha256:d6eb9be32fdc1800ce8d60bf83c481f6090bf7e45c729527685eaec8bcfa215c
          name: container-image
